// Code generated by go-swagger; DO NOT EDIT.

package cabwise

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dwardu89/tfl-api-swagger/models"
)

// CabwiseGetReader is a Reader for the CabwiseGet structure.
type CabwiseGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CabwiseGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCabwiseGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCabwiseGetOK creates a CabwiseGetOK with default headers values
func NewCabwiseGetOK() *CabwiseGetOK {
	return &CabwiseGetOK{}
}

/*CabwiseGetOK handles this case with default header values.

OK
*/
type CabwiseGetOK struct {
	Payload models.SystemObject
}

func (o *CabwiseGetOK) Error() string {
	return fmt.Sprintf("[GET /Cabwise/search][%d] cabwiseGetOK  %+v", 200, o.Payload)
}

func (o *CabwiseGetOK) GetPayload() models.SystemObject {
	return o.Payload
}

func (o *CabwiseGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
