// Code generated by go-swagger; DO NOT EDIT.

package road

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dwardu89/tfl-api-swagger/models"
)

// RoadDisruptionByIDReader is a Reader for the RoadDisruptionByID structure.
type RoadDisruptionByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RoadDisruptionByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRoadDisruptionByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRoadDisruptionByIDOK creates a RoadDisruptionByIDOK with default headers values
func NewRoadDisruptionByIDOK() *RoadDisruptionByIDOK {
	return &RoadDisruptionByIDOK{}
}

/*RoadDisruptionByIDOK handles this case with default header values.

OK
*/
type RoadDisruptionByIDOK struct {
	Payload *models.TflAPIPresentationEntitiesRoadDisruption
}

func (o *RoadDisruptionByIDOK) Error() string {
	return fmt.Sprintf("[GET /Road/all/Disruption/{disruptionIds}][%d] roadDisruptionByIdOK  %+v", 200, o.Payload)
}

func (o *RoadDisruptionByIDOK) GetPayload() *models.TflAPIPresentationEntitiesRoadDisruption {
	return o.Payload
}

func (o *RoadDisruptionByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TflAPIPresentationEntitiesRoadDisruption)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
