// Code generated by go-swagger; DO NOT EDIT.

package road

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// RoadMetaCategoriesReader is a Reader for the RoadMetaCategories structure.
type RoadMetaCategoriesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RoadMetaCategoriesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRoadMetaCategoriesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRoadMetaCategoriesOK creates a RoadMetaCategoriesOK with default headers values
func NewRoadMetaCategoriesOK() *RoadMetaCategoriesOK {
	return &RoadMetaCategoriesOK{}
}

/*RoadMetaCategoriesOK handles this case with default header values.

OK
*/
type RoadMetaCategoriesOK struct {
	Payload []string
}

func (o *RoadMetaCategoriesOK) Error() string {
	return fmt.Sprintf("[GET /Road/Meta/Categories][%d] roadMetaCategoriesOK  %+v", 200, o.Payload)
}

func (o *RoadMetaCategoriesOK) GetPayload() []string {
	return o.Payload
}

func (o *RoadMetaCategoriesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
