// Code generated by go-swagger; DO NOT EDIT.

package road

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dwardu89/tfl-api-swagger/models"
)

// RoadDisruptedStreetsReader is a Reader for the RoadDisruptedStreets structure.
type RoadDisruptedStreetsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RoadDisruptedStreetsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRoadDisruptedStreetsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRoadDisruptedStreetsOK creates a RoadDisruptedStreetsOK with default headers values
func NewRoadDisruptedStreetsOK() *RoadDisruptedStreetsOK {
	return &RoadDisruptedStreetsOK{}
}

/*RoadDisruptedStreetsOK handles this case with default header values.

OK
*/
type RoadDisruptedStreetsOK struct {
	Payload models.SystemObject
}

func (o *RoadDisruptedStreetsOK) Error() string {
	return fmt.Sprintf("[GET /Road/all/Street/Disruption][%d] roadDisruptedStreetsOK  %+v", 200, o.Payload)
}

func (o *RoadDisruptedStreetsOK) GetPayload() models.SystemObject {
	return o.Payload
}

func (o *RoadDisruptedStreetsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
