// Code generated by go-swagger; DO NOT EDIT.

package road

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dwardu89/tfl-api-swagger/models"
)

// RoadDisruptionReader is a Reader for the RoadDisruption structure.
type RoadDisruptionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RoadDisruptionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRoadDisruptionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRoadDisruptionOK creates a RoadDisruptionOK with default headers values
func NewRoadDisruptionOK() *RoadDisruptionOK {
	return &RoadDisruptionOK{}
}

/*RoadDisruptionOK handles this case with default header values.

OK
*/
type RoadDisruptionOK struct {
	Payload []*models.TflAPIPresentationEntitiesRoadDisruption
}

func (o *RoadDisruptionOK) Error() string {
	return fmt.Sprintf("[GET /Road/{ids}/Disruption][%d] roadDisruptionOK  %+v", 200, o.Payload)
}

func (o *RoadDisruptionOK) GetPayload() []*models.TflAPIPresentationEntitiesRoadDisruption {
	return o.Payload
}

func (o *RoadDisruptionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
