// Code generated by go-swagger; DO NOT EDIT.

package occupancy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewOccupancyGetBikePointsOccupanciesParams creates a new OccupancyGetBikePointsOccupanciesParams object
// with the default values initialized.
func NewOccupancyGetBikePointsOccupanciesParams() *OccupancyGetBikePointsOccupanciesParams {
	var ()
	return &OccupancyGetBikePointsOccupanciesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOccupancyGetBikePointsOccupanciesParamsWithTimeout creates a new OccupancyGetBikePointsOccupanciesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOccupancyGetBikePointsOccupanciesParamsWithTimeout(timeout time.Duration) *OccupancyGetBikePointsOccupanciesParams {
	var ()
	return &OccupancyGetBikePointsOccupanciesParams{

		timeout: timeout,
	}
}

// NewOccupancyGetBikePointsOccupanciesParamsWithContext creates a new OccupancyGetBikePointsOccupanciesParams object
// with the default values initialized, and the ability to set a context for a request
func NewOccupancyGetBikePointsOccupanciesParamsWithContext(ctx context.Context) *OccupancyGetBikePointsOccupanciesParams {
	var ()
	return &OccupancyGetBikePointsOccupanciesParams{

		Context: ctx,
	}
}

// NewOccupancyGetBikePointsOccupanciesParamsWithHTTPClient creates a new OccupancyGetBikePointsOccupanciesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOccupancyGetBikePointsOccupanciesParamsWithHTTPClient(client *http.Client) *OccupancyGetBikePointsOccupanciesParams {
	var ()
	return &OccupancyGetBikePointsOccupanciesParams{
		HTTPClient: client,
	}
}

/*OccupancyGetBikePointsOccupanciesParams contains all the parameters to send to the API endpoint
for the occupancy get bike points occupancies operation typically these are written to a http.Request
*/
type OccupancyGetBikePointsOccupanciesParams struct {

	/*Ids*/
	Ids []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the occupancy get bike points occupancies params
func (o *OccupancyGetBikePointsOccupanciesParams) WithTimeout(timeout time.Duration) *OccupancyGetBikePointsOccupanciesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the occupancy get bike points occupancies params
func (o *OccupancyGetBikePointsOccupanciesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the occupancy get bike points occupancies params
func (o *OccupancyGetBikePointsOccupanciesParams) WithContext(ctx context.Context) *OccupancyGetBikePointsOccupanciesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the occupancy get bike points occupancies params
func (o *OccupancyGetBikePointsOccupanciesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the occupancy get bike points occupancies params
func (o *OccupancyGetBikePointsOccupanciesParams) WithHTTPClient(client *http.Client) *OccupancyGetBikePointsOccupanciesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the occupancy get bike points occupancies params
func (o *OccupancyGetBikePointsOccupanciesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIds adds the ids to the occupancy get bike points occupancies params
func (o *OccupancyGetBikePointsOccupanciesParams) WithIds(ids []string) *OccupancyGetBikePointsOccupanciesParams {
	o.SetIds(ids)
	return o
}

// SetIds adds the ids to the occupancy get bike points occupancies params
func (o *OccupancyGetBikePointsOccupanciesParams) SetIds(ids []string) {
	o.Ids = ids
}

// WriteToRequest writes these params to a swagger request
func (o *OccupancyGetBikePointsOccupanciesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	valuesIds := o.Ids

	joinedIds := swag.JoinByFormat(valuesIds, "")
	// path array param ids
	// SetPathParam does not support variadric arguments, since we used JoinByFormat
	// we can send the first item in the array as it's all the items of the previous
	// array joined together
	if len(joinedIds) > 0 {
		if err := r.SetPathParam("ids", joinedIds[0]); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
