// Code generated by go-swagger; DO NOT EDIT.

package occupancy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dwardu89/tfl-api-swagger/models"
)

// OccupancyGetReader is a Reader for the OccupancyGet structure.
type OccupancyGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OccupancyGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOccupancyGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOccupancyGetOK creates a OccupancyGetOK with default headers values
func NewOccupancyGetOK() *OccupancyGetOK {
	return &OccupancyGetOK{}
}

/*OccupancyGetOK handles this case with default header values.

OK
*/
type OccupancyGetOK struct {
	Payload *models.TflAPIPresentationEntitiesCarParkOccupancy
}

func (o *OccupancyGetOK) Error() string {
	return fmt.Sprintf("[GET /Occupancy/CarPark/{id}][%d] occupancyGetOK  %+v", 200, o.Payload)
}

func (o *OccupancyGetOK) GetPayload() *models.TflAPIPresentationEntitiesCarParkOccupancy {
	return o.Payload
}

func (o *OccupancyGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TflAPIPresentationEntitiesCarParkOccupancy)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
