// Code generated by go-swagger; DO NOT EDIT.

package vehicle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewVehicleGetEmissionsSurchargeComplianceParams creates a new VehicleGetEmissionsSurchargeComplianceParams object
// with the default values initialized.
func NewVehicleGetEmissionsSurchargeComplianceParams() *VehicleGetEmissionsSurchargeComplianceParams {
	var ()
	return &VehicleGetEmissionsSurchargeComplianceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewVehicleGetEmissionsSurchargeComplianceParamsWithTimeout creates a new VehicleGetEmissionsSurchargeComplianceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewVehicleGetEmissionsSurchargeComplianceParamsWithTimeout(timeout time.Duration) *VehicleGetEmissionsSurchargeComplianceParams {
	var ()
	return &VehicleGetEmissionsSurchargeComplianceParams{

		timeout: timeout,
	}
}

// NewVehicleGetEmissionsSurchargeComplianceParamsWithContext creates a new VehicleGetEmissionsSurchargeComplianceParams object
// with the default values initialized, and the ability to set a context for a request
func NewVehicleGetEmissionsSurchargeComplianceParamsWithContext(ctx context.Context) *VehicleGetEmissionsSurchargeComplianceParams {
	var ()
	return &VehicleGetEmissionsSurchargeComplianceParams{

		Context: ctx,
	}
}

// NewVehicleGetEmissionsSurchargeComplianceParamsWithHTTPClient creates a new VehicleGetEmissionsSurchargeComplianceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewVehicleGetEmissionsSurchargeComplianceParamsWithHTTPClient(client *http.Client) *VehicleGetEmissionsSurchargeComplianceParams {
	var ()
	return &VehicleGetEmissionsSurchargeComplianceParams{
		HTTPClient: client,
	}
}

/*VehicleGetEmissionsSurchargeComplianceParams contains all the parameters to send to the API endpoint
for the vehicle get emissions surcharge compliance operation typically these are written to a http.Request
*/
type VehicleGetEmissionsSurchargeComplianceParams struct {

	/*Vrm
	  The Vehicle Registration Mark

	*/
	Vrm string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the vehicle get emissions surcharge compliance params
func (o *VehicleGetEmissionsSurchargeComplianceParams) WithTimeout(timeout time.Duration) *VehicleGetEmissionsSurchargeComplianceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the vehicle get emissions surcharge compliance params
func (o *VehicleGetEmissionsSurchargeComplianceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the vehicle get emissions surcharge compliance params
func (o *VehicleGetEmissionsSurchargeComplianceParams) WithContext(ctx context.Context) *VehicleGetEmissionsSurchargeComplianceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the vehicle get emissions surcharge compliance params
func (o *VehicleGetEmissionsSurchargeComplianceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the vehicle get emissions surcharge compliance params
func (o *VehicleGetEmissionsSurchargeComplianceParams) WithHTTPClient(client *http.Client) *VehicleGetEmissionsSurchargeComplianceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the vehicle get emissions surcharge compliance params
func (o *VehicleGetEmissionsSurchargeComplianceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithVrm adds the vrm to the vehicle get emissions surcharge compliance params
func (o *VehicleGetEmissionsSurchargeComplianceParams) WithVrm(vrm string) *VehicleGetEmissionsSurchargeComplianceParams {
	o.SetVrm(vrm)
	return o
}

// SetVrm adds the vrm to the vehicle get emissions surcharge compliance params
func (o *VehicleGetEmissionsSurchargeComplianceParams) SetVrm(vrm string) {
	o.Vrm = vrm
}

// WriteToRequest writes these params to a swagger request
func (o *VehicleGetEmissionsSurchargeComplianceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param vrm
	qrVrm := o.Vrm
	qVrm := qrVrm
	if qVrm != "" {
		if err := r.SetQueryParam("vrm", qVrm); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
