// Code generated by go-swagger; DO NOT EDIT.

package vehicle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewVehicleGetUlezComplianceParams creates a new VehicleGetUlezComplianceParams object
// with the default values initialized.
func NewVehicleGetUlezComplianceParams() *VehicleGetUlezComplianceParams {
	var ()
	return &VehicleGetUlezComplianceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewVehicleGetUlezComplianceParamsWithTimeout creates a new VehicleGetUlezComplianceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewVehicleGetUlezComplianceParamsWithTimeout(timeout time.Duration) *VehicleGetUlezComplianceParams {
	var ()
	return &VehicleGetUlezComplianceParams{

		timeout: timeout,
	}
}

// NewVehicleGetUlezComplianceParamsWithContext creates a new VehicleGetUlezComplianceParams object
// with the default values initialized, and the ability to set a context for a request
func NewVehicleGetUlezComplianceParamsWithContext(ctx context.Context) *VehicleGetUlezComplianceParams {
	var ()
	return &VehicleGetUlezComplianceParams{

		Context: ctx,
	}
}

// NewVehicleGetUlezComplianceParamsWithHTTPClient creates a new VehicleGetUlezComplianceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewVehicleGetUlezComplianceParamsWithHTTPClient(client *http.Client) *VehicleGetUlezComplianceParams {
	var ()
	return &VehicleGetUlezComplianceParams{
		HTTPClient: client,
	}
}

/*VehicleGetUlezComplianceParams contains all the parameters to send to the API endpoint
for the vehicle get ulez compliance operation typically these are written to a http.Request
*/
type VehicleGetUlezComplianceParams struct {

	/*Vrm
	  The Vehicle Registration Mark

	*/
	Vrm string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the vehicle get ulez compliance params
func (o *VehicleGetUlezComplianceParams) WithTimeout(timeout time.Duration) *VehicleGetUlezComplianceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the vehicle get ulez compliance params
func (o *VehicleGetUlezComplianceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the vehicle get ulez compliance params
func (o *VehicleGetUlezComplianceParams) WithContext(ctx context.Context) *VehicleGetUlezComplianceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the vehicle get ulez compliance params
func (o *VehicleGetUlezComplianceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the vehicle get ulez compliance params
func (o *VehicleGetUlezComplianceParams) WithHTTPClient(client *http.Client) *VehicleGetUlezComplianceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the vehicle get ulez compliance params
func (o *VehicleGetUlezComplianceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithVrm adds the vrm to the vehicle get ulez compliance params
func (o *VehicleGetUlezComplianceParams) WithVrm(vrm string) *VehicleGetUlezComplianceParams {
	o.SetVrm(vrm)
	return o
}

// SetVrm adds the vrm to the vehicle get ulez compliance params
func (o *VehicleGetUlezComplianceParams) SetVrm(vrm string) {
	o.Vrm = vrm
}

// WriteToRequest writes these params to a swagger request
func (o *VehicleGetUlezComplianceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param vrm
	qrVrm := o.Vrm
	qVrm := qrVrm
	if qVrm != "" {
		if err := r.SetQueryParam("vrm", qVrm); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
