// Code generated by go-swagger; DO NOT EDIT.

package vehicle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dwardu89/tfl-api-swagger/models"
)

// VehicleGetReader is a Reader for the VehicleGet structure.
type VehicleGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VehicleGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewVehicleGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewVehicleGetOK creates a VehicleGetOK with default headers values
func NewVehicleGetOK() *VehicleGetOK {
	return &VehicleGetOK{}
}

/*VehicleGetOK handles this case with default header values.

OK
*/
type VehicleGetOK struct {
	Payload []*models.TflAPIPresentationEntitiesPrediction
}

func (o *VehicleGetOK) Error() string {
	return fmt.Sprintf("[GET /Vehicle/{ids}/Arrivals][%d] vehicleGetOK  %+v", 200, o.Payload)
}

func (o *VehicleGetOK) GetPayload() []*models.TflAPIPresentationEntitiesPrediction {
	return o.Payload
}

func (o *VehicleGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
