// Code generated by go-swagger; DO NOT EDIT.

package vehicle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new vehicle API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for vehicle API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
VehicleGet gets the predictions for a given list of vehicle Id s
*/
func (a *Client) VehicleGet(params *VehicleGetParams) (*VehicleGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewVehicleGetParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Vehicle_Get",
		Method:             "GET",
		PathPattern:        "/Vehicle/{ids}/Arrivals",
		ProducesMediaTypes: []string{"application/json", "application/xml", "text/json", "text/xml"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &VehicleGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*VehicleGetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Vehicle_Get: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
VehicleGetEmissionsSurchargeCompliance gets the emissions surcharge compliance for the vehicle
*/
func (a *Client) VehicleGetEmissionsSurchargeCompliance(params *VehicleGetEmissionsSurchargeComplianceParams) (*VehicleGetEmissionsSurchargeComplianceOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewVehicleGetEmissionsSurchargeComplianceParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Vehicle_GetEmissionsSurchargeCompliance",
		Method:             "GET",
		PathPattern:        "/Vehicle/EmissionSurcharge",
		ProducesMediaTypes: []string{"application/json", "application/xml", "text/json", "text/xml"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &VehicleGetEmissionsSurchargeComplianceReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*VehicleGetEmissionsSurchargeComplianceOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Vehicle_GetEmissionsSurchargeCompliance: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
VehicleGetUlezCompliance gets the ulez surcharge compliance for the vehicle
*/
func (a *Client) VehicleGetUlezCompliance(params *VehicleGetUlezComplianceParams) (*VehicleGetUlezComplianceOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewVehicleGetUlezComplianceParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Vehicle_GetUlezCompliance",
		Method:             "GET",
		PathPattern:        "/Vehicle/UlezCompliance",
		ProducesMediaTypes: []string{"application/json", "application/xml", "text/json", "text/xml"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &VehicleGetUlezComplianceReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*VehicleGetUlezComplianceOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Vehicle_GetUlezCompliance: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
