// Code generated by go-swagger; DO NOT EDIT.

package stop_point

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dwardu89/tfl-api-swagger/models"
)

// StopPointArrivalsReader is a Reader for the StopPointArrivals structure.
type StopPointArrivalsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StopPointArrivalsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStopPointArrivalsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewStopPointArrivalsOK creates a StopPointArrivalsOK with default headers values
func NewStopPointArrivalsOK() *StopPointArrivalsOK {
	return &StopPointArrivalsOK{}
}

/*StopPointArrivalsOK handles this case with default header values.

OK
*/
type StopPointArrivalsOK struct {
	Payload []*models.TflAPIPresentationEntitiesPrediction
}

func (o *StopPointArrivalsOK) Error() string {
	return fmt.Sprintf("[GET /StopPoint/{id}/Arrivals][%d] stopPointArrivalsOK  %+v", 200, o.Payload)
}

func (o *StopPointArrivalsOK) GetPayload() []*models.TflAPIPresentationEntitiesPrediction {
	return o.Payload
}

func (o *StopPointArrivalsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
