// Code generated by go-swagger; DO NOT EDIT.

package stop_point

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dwardu89/tfl-api-swagger/models"
)

// StopPointGetServiceTypesReader is a Reader for the StopPointGetServiceTypes structure.
type StopPointGetServiceTypesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StopPointGetServiceTypesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStopPointGetServiceTypesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewStopPointGetServiceTypesOK creates a StopPointGetServiceTypesOK with default headers values
func NewStopPointGetServiceTypesOK() *StopPointGetServiceTypesOK {
	return &StopPointGetServiceTypesOK{}
}

/*StopPointGetServiceTypesOK handles this case with default header values.

OK
*/
type StopPointGetServiceTypesOK struct {
	Payload []*models.TflAPIPresentationEntitiesLineServiceType
}

func (o *StopPointGetServiceTypesOK) Error() string {
	return fmt.Sprintf("[GET /StopPoint/ServiceTypes][%d] stopPointGetServiceTypesOK  %+v", 200, o.Payload)
}

func (o *StopPointGetServiceTypesOK) GetPayload() []*models.TflAPIPresentationEntitiesLineServiceType {
	return o.Payload
}

func (o *StopPointGetServiceTypesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
