// Code generated by go-swagger; DO NOT EDIT.

package stop_point

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// StopPointMetaStopTypesReader is a Reader for the StopPointMetaStopTypes structure.
type StopPointMetaStopTypesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StopPointMetaStopTypesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStopPointMetaStopTypesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewStopPointMetaStopTypesOK creates a StopPointMetaStopTypesOK with default headers values
func NewStopPointMetaStopTypesOK() *StopPointMetaStopTypesOK {
	return &StopPointMetaStopTypesOK{}
}

/*StopPointMetaStopTypesOK handles this case with default header values.

OK
*/
type StopPointMetaStopTypesOK struct {
	Payload []string
}

func (o *StopPointMetaStopTypesOK) Error() string {
	return fmt.Sprintf("[GET /StopPoint/Meta/StopTypes][%d] stopPointMetaStopTypesOK  %+v", 200, o.Payload)
}

func (o *StopPointMetaStopTypesOK) GetPayload() []string {
	return o.Payload
}

func (o *StopPointMetaStopTypesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
