// Code generated by go-swagger; DO NOT EDIT.

package stop_point

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewStopPointGetCarParksByIDParams creates a new StopPointGetCarParksByIDParams object
// with the default values initialized.
func NewStopPointGetCarParksByIDParams() *StopPointGetCarParksByIDParams {
	var ()
	return &StopPointGetCarParksByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewStopPointGetCarParksByIDParamsWithTimeout creates a new StopPointGetCarParksByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStopPointGetCarParksByIDParamsWithTimeout(timeout time.Duration) *StopPointGetCarParksByIDParams {
	var ()
	return &StopPointGetCarParksByIDParams{

		timeout: timeout,
	}
}

// NewStopPointGetCarParksByIDParamsWithContext creates a new StopPointGetCarParksByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewStopPointGetCarParksByIDParamsWithContext(ctx context.Context) *StopPointGetCarParksByIDParams {
	var ()
	return &StopPointGetCarParksByIDParams{

		Context: ctx,
	}
}

// NewStopPointGetCarParksByIDParamsWithHTTPClient creates a new StopPointGetCarParksByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewStopPointGetCarParksByIDParamsWithHTTPClient(client *http.Client) *StopPointGetCarParksByIDParams {
	var ()
	return &StopPointGetCarParksByIDParams{
		HTTPClient: client,
	}
}

/*StopPointGetCarParksByIDParams contains all the parameters to send to the API endpoint
for the stop point get car parks by Id operation typically these are written to a http.Request
*/
type StopPointGetCarParksByIDParams struct {

	/*StopPointID
	  stopPointId is required to get the car parks.

	*/
	StopPointID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the stop point get car parks by Id params
func (o *StopPointGetCarParksByIDParams) WithTimeout(timeout time.Duration) *StopPointGetCarParksByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stop point get car parks by Id params
func (o *StopPointGetCarParksByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the stop point get car parks by Id params
func (o *StopPointGetCarParksByIDParams) WithContext(ctx context.Context) *StopPointGetCarParksByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stop point get car parks by Id params
func (o *StopPointGetCarParksByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the stop point get car parks by Id params
func (o *StopPointGetCarParksByIDParams) WithHTTPClient(client *http.Client) *StopPointGetCarParksByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the stop point get car parks by Id params
func (o *StopPointGetCarParksByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithStopPointID adds the stopPointID to the stop point get car parks by Id params
func (o *StopPointGetCarParksByIDParams) WithStopPointID(stopPointID string) *StopPointGetCarParksByIDParams {
	o.SetStopPointID(stopPointID)
	return o
}

// SetStopPointID adds the stopPointId to the stop point get car parks by Id params
func (o *StopPointGetCarParksByIDParams) SetStopPointID(stopPointID string) {
	o.StopPointID = stopPointID
}

// WriteToRequest writes these params to a swagger request
func (o *StopPointGetCarParksByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param stopPointId
	if err := r.SetPathParam("stopPointId", o.StopPointID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
