// Code generated by go-swagger; DO NOT EDIT.

package stop_point

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dwardu89/tfl-api-swagger/models"
)

// StopPointGetBySmsReader is a Reader for the StopPointGetBySms structure.
type StopPointGetBySmsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StopPointGetBySmsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStopPointGetBySmsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewStopPointGetBySmsOK creates a StopPointGetBySmsOK with default headers values
func NewStopPointGetBySmsOK() *StopPointGetBySmsOK {
	return &StopPointGetBySmsOK{}
}

/*StopPointGetBySmsOK handles this case with default header values.

OK
*/
type StopPointGetBySmsOK struct {
	Payload models.SystemObject
}

func (o *StopPointGetBySmsOK) Error() string {
	return fmt.Sprintf("[GET /StopPoint/Sms/{id}][%d] stopPointGetBySmsOK  %+v", 200, o.Payload)
}

func (o *StopPointGetBySmsOK) GetPayload() models.SystemObject {
	return o.Payload
}

func (o *StopPointGetBySmsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
