// Code generated by go-swagger; DO NOT EDIT.

package stop_point

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dwardu89/tfl-api-swagger/models"
)

// StopPointGetTaxiRanksByIdsReader is a Reader for the StopPointGetTaxiRanksByIds structure.
type StopPointGetTaxiRanksByIdsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StopPointGetTaxiRanksByIdsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStopPointGetTaxiRanksByIdsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewStopPointGetTaxiRanksByIdsOK creates a StopPointGetTaxiRanksByIdsOK with default headers values
func NewStopPointGetTaxiRanksByIdsOK() *StopPointGetTaxiRanksByIdsOK {
	return &StopPointGetTaxiRanksByIdsOK{}
}

/*StopPointGetTaxiRanksByIdsOK handles this case with default header values.

OK
*/
type StopPointGetTaxiRanksByIdsOK struct {
	Payload []*models.TflAPIPresentationEntitiesPlace
}

func (o *StopPointGetTaxiRanksByIdsOK) Error() string {
	return fmt.Sprintf("[GET /StopPoint/{stopPointId}/TaxiRanks][%d] stopPointGetTaxiRanksByIdsOK  %+v", 200, o.Payload)
}

func (o *StopPointGetTaxiRanksByIdsOK) GetPayload() []*models.TflAPIPresentationEntitiesPlace {
	return o.Payload
}

func (o *StopPointGetTaxiRanksByIdsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
