// Code generated by go-swagger; DO NOT EDIT.

package stop_point

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dwardu89/tfl-api-swagger/models"
)

// StopPointGetByGeoPointReader is a Reader for the StopPointGetByGeoPoint structure.
type StopPointGetByGeoPointReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StopPointGetByGeoPointReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStopPointGetByGeoPointOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewStopPointGetByGeoPointOK creates a StopPointGetByGeoPointOK with default headers values
func NewStopPointGetByGeoPointOK() *StopPointGetByGeoPointOK {
	return &StopPointGetByGeoPointOK{}
}

/*StopPointGetByGeoPointOK handles this case with default header values.

OK
*/
type StopPointGetByGeoPointOK struct {
	Payload *models.TflAPIPresentationEntitiesStopPointsResponse
}

func (o *StopPointGetByGeoPointOK) Error() string {
	return fmt.Sprintf("[GET /StopPoint][%d] stopPointGetByGeoPointOK  %+v", 200, o.Payload)
}

func (o *StopPointGetByGeoPointOK) GetPayload() *models.TflAPIPresentationEntitiesStopPointsResponse {
	return o.Payload
}

func (o *StopPointGetByGeoPointOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TflAPIPresentationEntitiesStopPointsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
