// Code generated by go-swagger; DO NOT EDIT.

package stop_point

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dwardu89/tfl-api-swagger/models"
)

// StopPointSearchReader is a Reader for the StopPointSearch structure.
type StopPointSearchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StopPointSearchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStopPointSearchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewStopPointSearchOK creates a StopPointSearchOK with default headers values
func NewStopPointSearchOK() *StopPointSearchOK {
	return &StopPointSearchOK{}
}

/*StopPointSearchOK handles this case with default header values.

OK
*/
type StopPointSearchOK struct {
	Payload *models.TflAPIPresentationEntitiesSearchResponse
}

func (o *StopPointSearchOK) Error() string {
	return fmt.Sprintf("[GET /StopPoint/Search/{query}][%d] stopPointSearchOK  %+v", 200, o.Payload)
}

func (o *StopPointSearchOK) GetPayload() *models.TflAPIPresentationEntitiesSearchResponse {
	return o.Payload
}

func (o *StopPointSearchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TflAPIPresentationEntitiesSearchResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
