// Code generated by go-swagger; DO NOT EDIT.

package stop_point

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dwardu89/tfl-api-swagger/models"
)

// StopPointGetByTypeWithPaginationReader is a Reader for the StopPointGetByTypeWithPagination structure.
type StopPointGetByTypeWithPaginationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StopPointGetByTypeWithPaginationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStopPointGetByTypeWithPaginationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewStopPointGetByTypeWithPaginationOK creates a StopPointGetByTypeWithPaginationOK with default headers values
func NewStopPointGetByTypeWithPaginationOK() *StopPointGetByTypeWithPaginationOK {
	return &StopPointGetByTypeWithPaginationOK{}
}

/*StopPointGetByTypeWithPaginationOK handles this case with default header values.

OK
*/
type StopPointGetByTypeWithPaginationOK struct {
	Payload []*models.TflAPIPresentationEntitiesStopPoint
}

func (o *StopPointGetByTypeWithPaginationOK) Error() string {
	return fmt.Sprintf("[GET /StopPoint/Type/{types}/page/{page}][%d] stopPointGetByTypeWithPaginationOK  %+v", 200, o.Payload)
}

func (o *StopPointGetByTypeWithPaginationOK) GetPayload() []*models.TflAPIPresentationEntitiesStopPoint {
	return o.Payload
}

func (o *StopPointGetByTypeWithPaginationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
