// Code generated by go-swagger; DO NOT EDIT.

package stop_point

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dwardu89/tfl-api-swagger/models"
)

// StopPointGetCarParksByIDReader is a Reader for the StopPointGetCarParksByID structure.
type StopPointGetCarParksByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StopPointGetCarParksByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStopPointGetCarParksByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewStopPointGetCarParksByIDOK creates a StopPointGetCarParksByIDOK with default headers values
func NewStopPointGetCarParksByIDOK() *StopPointGetCarParksByIDOK {
	return &StopPointGetCarParksByIDOK{}
}

/*StopPointGetCarParksByIDOK handles this case with default header values.

OK
*/
type StopPointGetCarParksByIDOK struct {
	Payload []*models.TflAPIPresentationEntitiesPlace
}

func (o *StopPointGetCarParksByIDOK) Error() string {
	return fmt.Sprintf("[GET /StopPoint/{stopPointId}/CarParks][%d] stopPointGetCarParksByIdOK  %+v", 200, o.Payload)
}

func (o *StopPointGetCarParksByIDOK) GetPayload() []*models.TflAPIPresentationEntitiesPlace {
	return o.Payload
}

func (o *StopPointGetCarParksByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
