// Code generated by go-swagger; DO NOT EDIT.

package mode

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dwardu89/tfl-api-swagger/models"
)

// ModeArrivalsReader is a Reader for the ModeArrivals structure.
type ModeArrivalsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ModeArrivalsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewModeArrivalsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewModeArrivalsOK creates a ModeArrivalsOK with default headers values
func NewModeArrivalsOK() *ModeArrivalsOK {
	return &ModeArrivalsOK{}
}

/*ModeArrivalsOK handles this case with default header values.

OK
*/
type ModeArrivalsOK struct {
	Payload []*models.TflAPIPresentationEntitiesPrediction
}

func (o *ModeArrivalsOK) Error() string {
	return fmt.Sprintf("[GET /Mode/{mode}/Arrivals][%d] modeArrivalsOK  %+v", 200, o.Payload)
}

func (o *ModeArrivalsOK) GetPayload() []*models.TflAPIPresentationEntitiesPrediction {
	return o.Payload
}

func (o *ModeArrivalsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
