// Code generated by go-swagger; DO NOT EDIT.

package mode

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dwardu89/tfl-api-swagger/models"
)

// ModeGetActiveServiceTypesReader is a Reader for the ModeGetActiveServiceTypes structure.
type ModeGetActiveServiceTypesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ModeGetActiveServiceTypesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewModeGetActiveServiceTypesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewModeGetActiveServiceTypesOK creates a ModeGetActiveServiceTypesOK with default headers values
func NewModeGetActiveServiceTypesOK() *ModeGetActiveServiceTypesOK {
	return &ModeGetActiveServiceTypesOK{}
}

/*ModeGetActiveServiceTypesOK handles this case with default header values.

OK
*/
type ModeGetActiveServiceTypesOK struct {
	Payload []*models.TflAPIPresentationEntitiesActiveServiceType
}

func (o *ModeGetActiveServiceTypesOK) Error() string {
	return fmt.Sprintf("[GET /Mode/ActiveServiceTypes][%d] modeGetActiveServiceTypesOK  %+v", 200, o.Payload)
}

func (o *ModeGetActiveServiceTypesOK) GetPayload() []*models.TflAPIPresentationEntitiesActiveServiceType {
	return o.Payload
}

func (o *ModeGetActiveServiceTypesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
