// Code generated by go-swagger; DO NOT EDIT.

package mode

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new mode API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for mode API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
ModeArrivals gets the next arrival predictions for all stops of a given mode
*/
func (a *Client) ModeArrivals(params *ModeArrivalsParams) (*ModeArrivalsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewModeArrivalsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Mode_Arrivals",
		Method:             "GET",
		PathPattern:        "/Mode/{mode}/Arrivals",
		ProducesMediaTypes: []string{"application/json", "application/xml", "text/json", "text/xml"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ModeArrivalsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ModeArrivalsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Mode_Arrivals: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
ModeGetActiveServiceTypes returns the service type active for a mode currently only supports tube
*/
func (a *Client) ModeGetActiveServiceTypes(params *ModeGetActiveServiceTypesParams) (*ModeGetActiveServiceTypesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewModeGetActiveServiceTypesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Mode_GetActiveServiceTypes",
		Method:             "GET",
		PathPattern:        "/Mode/ActiveServiceTypes",
		ProducesMediaTypes: []string{"application/json", "application/xml", "text/json", "text/xml"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ModeGetActiveServiceTypesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ModeGetActiveServiceTypesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Mode_GetActiveServiceTypes: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
