// Code generated by go-swagger; DO NOT EDIT.

package travel_time

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dwardu89/tfl-api-swagger/models"
)

// TravelTimeGetOverlayReader is a Reader for the TravelTimeGetOverlay structure.
type TravelTimeGetOverlayReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TravelTimeGetOverlayReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTravelTimeGetOverlayOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewTravelTimeGetOverlayOK creates a TravelTimeGetOverlayOK with default headers values
func NewTravelTimeGetOverlayOK() *TravelTimeGetOverlayOK {
	return &TravelTimeGetOverlayOK{}
}

/*TravelTimeGetOverlayOK handles this case with default header values.

OK
*/
type TravelTimeGetOverlayOK struct {
	Payload models.SystemObject
}

func (o *TravelTimeGetOverlayOK) Error() string {
	return fmt.Sprintf("[GET /TravelTimes/overlay/{z}/mapcenter/{mapCenterLat}/{mapCenterLon}/pinlocation/{pinLat}/{pinLon}/dimensions/{width}/{height}][%d] travelTimeGetOverlayOK  %+v", 200, o.Payload)
}

func (o *TravelTimeGetOverlayOK) GetPayload() models.SystemObject {
	return o.Payload
}

func (o *TravelTimeGetOverlayOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
