// Code generated by go-swagger; DO NOT EDIT.

package travel_time

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new travel time API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for travel time API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
TravelTimeGetCompareOverlay gets the travel time overlay
*/
func (a *Client) TravelTimeGetCompareOverlay(params *TravelTimeGetCompareOverlayParams) (*TravelTimeGetCompareOverlayOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewTravelTimeGetCompareOverlayParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "TravelTime_GetCompareOverlay",
		Method:             "GET",
		PathPattern:        "/TravelTimes/compareOverlay/{z}/mapcenter/{mapCenterLat}/{mapCenterLon}/pinlocation/{pinLat}/{pinLon}/dimensions/{width}/{height}",
		ProducesMediaTypes: []string{"application/json", "application/xml", "text/json", "text/xml"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &TravelTimeGetCompareOverlayReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*TravelTimeGetCompareOverlayOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for TravelTime_GetCompareOverlay: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
TravelTimeGetOverlay gets the travel time overlay
*/
func (a *Client) TravelTimeGetOverlay(params *TravelTimeGetOverlayParams) (*TravelTimeGetOverlayOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewTravelTimeGetOverlayParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "TravelTime_GetOverlay",
		Method:             "GET",
		PathPattern:        "/TravelTimes/overlay/{z}/mapcenter/{mapCenterLat}/{mapCenterLon}/pinlocation/{pinLat}/{pinLon}/dimensions/{width}/{height}",
		ProducesMediaTypes: []string{"application/json", "application/xml", "text/json", "text/xml"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &TravelTimeGetOverlayReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*TravelTimeGetOverlayOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for TravelTime_GetOverlay: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
