// Code generated by go-swagger; DO NOT EDIT.

package bike_point

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dwardu89/tfl-api-swagger/models"
)

// BikePointGetReader is a Reader for the BikePointGet structure.
type BikePointGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BikePointGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewBikePointGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewBikePointGetOK creates a BikePointGetOK with default headers values
func NewBikePointGetOK() *BikePointGetOK {
	return &BikePointGetOK{}
}

/*BikePointGetOK handles this case with default header values.

OK
*/
type BikePointGetOK struct {
	Payload *models.TflAPIPresentationEntitiesPlace
}

func (o *BikePointGetOK) Error() string {
	return fmt.Sprintf("[GET /BikePoint/{id}][%d] bikePointGetOK  %+v", 200, o.Payload)
}

func (o *BikePointGetOK) GetPayload() *models.TflAPIPresentationEntitiesPlace {
	return o.Payload
}

func (o *BikePointGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TflAPIPresentationEntitiesPlace)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
