// Code generated by go-swagger; DO NOT EDIT.

package bike_point

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dwardu89/tfl-api-swagger/models"
)

// BikePointGetAllReader is a Reader for the BikePointGetAll structure.
type BikePointGetAllReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BikePointGetAllReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewBikePointGetAllOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewBikePointGetAllOK creates a BikePointGetAllOK with default headers values
func NewBikePointGetAllOK() *BikePointGetAllOK {
	return &BikePointGetAllOK{}
}

/*BikePointGetAllOK handles this case with default header values.

OK
*/
type BikePointGetAllOK struct {
	Payload []*models.TflAPIPresentationEntitiesPlace
}

func (o *BikePointGetAllOK) Error() string {
	return fmt.Sprintf("[GET /BikePoint][%d] bikePointGetAllOK  %+v", 200, o.Payload)
}

func (o *BikePointGetAllOK) GetPayload() []*models.TflAPIPresentationEntitiesPlace {
	return o.Payload
}

func (o *BikePointGetAllOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
