// Code generated by go-swagger; DO NOT EDIT.

package line

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dwardu89/tfl-api-swagger/models"
)

// LineStopPointsReader is a Reader for the LineStopPoints structure.
type LineStopPointsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LineStopPointsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLineStopPointsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewLineStopPointsOK creates a LineStopPointsOK with default headers values
func NewLineStopPointsOK() *LineStopPointsOK {
	return &LineStopPointsOK{}
}

/*LineStopPointsOK handles this case with default header values.

OK
*/
type LineStopPointsOK struct {
	Payload []*models.TflAPIPresentationEntitiesStopPoint
}

func (o *LineStopPointsOK) Error() string {
	return fmt.Sprintf("[GET /Line/{id}/StopPoints][%d] lineStopPointsOK  %+v", 200, o.Payload)
}

func (o *LineStopPointsOK) GetPayload() []*models.TflAPIPresentationEntitiesStopPoint {
	return o.Payload
}

func (o *LineStopPointsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
