// Code generated by go-swagger; DO NOT EDIT.

package line

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dwardu89/tfl-api-swagger/models"
)

// LineSearchReader is a Reader for the LineSearch structure.
type LineSearchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LineSearchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLineSearchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewLineSearchOK creates a LineSearchOK with default headers values
func NewLineSearchOK() *LineSearchOK {
	return &LineSearchOK{}
}

/*LineSearchOK handles this case with default header values.

OK
*/
type LineSearchOK struct {
	Payload *models.TflAPIPresentationEntitiesRouteSearchResponse
}

func (o *LineSearchOK) Error() string {
	return fmt.Sprintf("[GET /Line/Search/{query}][%d] lineSearchOK  %+v", 200, o.Payload)
}

func (o *LineSearchOK) GetPayload() *models.TflAPIPresentationEntitiesRouteSearchResponse {
	return o.Payload
}

func (o *LineSearchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TflAPIPresentationEntitiesRouteSearchResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
