// Code generated by go-swagger; DO NOT EDIT.

package line

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dwardu89/tfl-api-swagger/models"
)

// LineRouteSequenceReader is a Reader for the LineRouteSequence structure.
type LineRouteSequenceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LineRouteSequenceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLineRouteSequenceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewLineRouteSequenceOK creates a LineRouteSequenceOK with default headers values
func NewLineRouteSequenceOK() *LineRouteSequenceOK {
	return &LineRouteSequenceOK{}
}

/*LineRouteSequenceOK handles this case with default header values.

OK
*/
type LineRouteSequenceOK struct {
	Payload *models.TflAPIPresentationEntitiesRouteSequence
}

func (o *LineRouteSequenceOK) Error() string {
	return fmt.Sprintf("[GET /Line/{id}/Route/Sequence/{direction}][%d] lineRouteSequenceOK  %+v", 200, o.Payload)
}

func (o *LineRouteSequenceOK) GetPayload() *models.TflAPIPresentationEntitiesRouteSequence {
	return o.Payload
}

func (o *LineRouteSequenceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TflAPIPresentationEntitiesRouteSequence)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
