// Code generated by go-swagger; DO NOT EDIT.

package line

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dwardu89/tfl-api-swagger/models"
)

// LineTimetableToReader is a Reader for the LineTimetableTo structure.
type LineTimetableToReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LineTimetableToReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLineTimetableToOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewLineTimetableToOK creates a LineTimetableToOK with default headers values
func NewLineTimetableToOK() *LineTimetableToOK {
	return &LineTimetableToOK{}
}

/*LineTimetableToOK handles this case with default header values.

OK
*/
type LineTimetableToOK struct {
	Payload *models.TflAPIPresentationEntitiesTimetableResponse
}

func (o *LineTimetableToOK) Error() string {
	return fmt.Sprintf("[GET /Line/{id}/Timetable/{fromStopPointId}/to/{toStopPointId}][%d] lineTimetableToOK  %+v", 200, o.Payload)
}

func (o *LineTimetableToOK) GetPayload() *models.TflAPIPresentationEntitiesTimetableResponse {
	return o.Payload
}

func (o *LineTimetableToOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TflAPIPresentationEntitiesTimetableResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
