// Code generated by go-swagger; DO NOT EDIT.

package line

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dwardu89/tfl-api-swagger/models"
)

// LineTimetableReader is a Reader for the LineTimetable structure.
type LineTimetableReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LineTimetableReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLineTimetableOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewLineTimetableOK creates a LineTimetableOK with default headers values
func NewLineTimetableOK() *LineTimetableOK {
	return &LineTimetableOK{}
}

/*LineTimetableOK handles this case with default header values.

OK
*/
type LineTimetableOK struct {
	Payload *models.TflAPIPresentationEntitiesTimetableResponse
}

func (o *LineTimetableOK) Error() string {
	return fmt.Sprintf("[GET /Line/{id}/Timetable/{fromStopPointId}][%d] lineTimetableOK  %+v", 200, o.Payload)
}

func (o *LineTimetableOK) GetPayload() *models.TflAPIPresentationEntitiesTimetableResponse {
	return o.Payload
}

func (o *LineTimetableOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TflAPIPresentationEntitiesTimetableResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
