// Code generated by go-swagger; DO NOT EDIT.

package line

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dwardu89/tfl-api-swagger/models"
)

// LineStatusByIdsReader is a Reader for the LineStatusByIds structure.
type LineStatusByIdsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LineStatusByIdsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLineStatusByIdsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewLineStatusByIdsOK creates a LineStatusByIdsOK with default headers values
func NewLineStatusByIdsOK() *LineStatusByIdsOK {
	return &LineStatusByIdsOK{}
}

/*LineStatusByIdsOK handles this case with default header values.

OK
*/
type LineStatusByIdsOK struct {
	Payload []*models.TflAPIPresentationEntitiesLine
}

func (o *LineStatusByIdsOK) Error() string {
	return fmt.Sprintf("[GET /Line/{ids}/Status][%d] lineStatusByIdsOK  %+v", 200, o.Payload)
}

func (o *LineStatusByIdsOK) GetPayload() []*models.TflAPIPresentationEntitiesLine {
	return o.Payload
}

func (o *LineStatusByIdsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
