// Code generated by go-swagger; DO NOT EDIT.

package line

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dwardu89/tfl-api-swagger/models"
)

// LineDisruptionReader is a Reader for the LineDisruption structure.
type LineDisruptionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LineDisruptionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLineDisruptionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewLineDisruptionOK creates a LineDisruptionOK with default headers values
func NewLineDisruptionOK() *LineDisruptionOK {
	return &LineDisruptionOK{}
}

/*LineDisruptionOK handles this case with default header values.

OK
*/
type LineDisruptionOK struct {
	Payload []*models.TflAPIPresentationEntitiesDisruption
}

func (o *LineDisruptionOK) Error() string {
	return fmt.Sprintf("[GET /Line/{ids}/Disruption][%d] lineDisruptionOK  %+v", 200, o.Payload)
}

func (o *LineDisruptionOK) GetPayload() []*models.TflAPIPresentationEntitiesDisruption {
	return o.Payload
}

func (o *LineDisruptionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
