// Code generated by go-swagger; DO NOT EDIT.

package line

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dwardu89/tfl-api-swagger/models"
)

// LineDisruptionByModeReader is a Reader for the LineDisruptionByMode structure.
type LineDisruptionByModeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LineDisruptionByModeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLineDisruptionByModeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewLineDisruptionByModeOK creates a LineDisruptionByModeOK with default headers values
func NewLineDisruptionByModeOK() *LineDisruptionByModeOK {
	return &LineDisruptionByModeOK{}
}

/*LineDisruptionByModeOK handles this case with default header values.

OK
*/
type LineDisruptionByModeOK struct {
	Payload []*models.TflAPIPresentationEntitiesDisruption
}

func (o *LineDisruptionByModeOK) Error() string {
	return fmt.Sprintf("[GET /Line/Mode/{modes}/Disruption][%d] lineDisruptionByModeOK  %+v", 200, o.Payload)
}

func (o *LineDisruptionByModeOK) GetPayload() []*models.TflAPIPresentationEntitiesDisruption {
	return o.Payload
}

func (o *LineDisruptionByModeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
