// Code generated by go-swagger; DO NOT EDIT.

package line

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dwardu89/tfl-api-swagger/models"
)

// LineArrivalsReader is a Reader for the LineArrivals structure.
type LineArrivalsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LineArrivalsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLineArrivalsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewLineArrivalsOK creates a LineArrivalsOK with default headers values
func NewLineArrivalsOK() *LineArrivalsOK {
	return &LineArrivalsOK{}
}

/*LineArrivalsOK handles this case with default header values.

OK
*/
type LineArrivalsOK struct {
	Payload []*models.TflAPIPresentationEntitiesPrediction
}

func (o *LineArrivalsOK) Error() string {
	return fmt.Sprintf("[GET /Line/{ids}/Arrivals/{stopPointId}][%d] lineArrivalsOK  %+v", 200, o.Payload)
}

func (o *LineArrivalsOK) GetPayload() []*models.TflAPIPresentationEntitiesPrediction {
	return o.Payload
}

func (o *LineArrivalsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
