// Code generated by go-swagger; DO NOT EDIT.

package line

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// LineMetaServiceTypesReader is a Reader for the LineMetaServiceTypes structure.
type LineMetaServiceTypesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LineMetaServiceTypesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLineMetaServiceTypesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewLineMetaServiceTypesOK creates a LineMetaServiceTypesOK with default headers values
func NewLineMetaServiceTypesOK() *LineMetaServiceTypesOK {
	return &LineMetaServiceTypesOK{}
}

/*LineMetaServiceTypesOK handles this case with default header values.

OK
*/
type LineMetaServiceTypesOK struct {
	Payload []string
}

func (o *LineMetaServiceTypesOK) Error() string {
	return fmt.Sprintf("[GET /Line/Meta/ServiceTypes][%d] lineMetaServiceTypesOK  %+v", 200, o.Payload)
}

func (o *LineMetaServiceTypesOK) GetPayload() []string {
	return o.Payload
}

func (o *LineMetaServiceTypesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
