// Code generated by go-swagger; DO NOT EDIT.

package line

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewLineStatusByIdsParams creates a new LineStatusByIdsParams object
// with the default values initialized.
func NewLineStatusByIdsParams() *LineStatusByIdsParams {
	var ()
	return &LineStatusByIdsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLineStatusByIdsParamsWithTimeout creates a new LineStatusByIdsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLineStatusByIdsParamsWithTimeout(timeout time.Duration) *LineStatusByIdsParams {
	var ()
	return &LineStatusByIdsParams{

		timeout: timeout,
	}
}

// NewLineStatusByIdsParamsWithContext creates a new LineStatusByIdsParams object
// with the default values initialized, and the ability to set a context for a request
func NewLineStatusByIdsParamsWithContext(ctx context.Context) *LineStatusByIdsParams {
	var ()
	return &LineStatusByIdsParams{

		Context: ctx,
	}
}

// NewLineStatusByIdsParamsWithHTTPClient creates a new LineStatusByIdsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewLineStatusByIdsParamsWithHTTPClient(client *http.Client) *LineStatusByIdsParams {
	var ()
	return &LineStatusByIdsParams{
		HTTPClient: client,
	}
}

/*LineStatusByIdsParams contains all the parameters to send to the API endpoint
for the line status by ids operation typically these are written to a http.Request
*/
type LineStatusByIdsParams struct {

	/*Detail
	  Include details of the disruptions that are causing the line status including the affected stops and routes

	*/
	Detail *bool
	/*Ids
	  A comma-separated list of line ids e.g. victoria,circle,N133. Max. approx. 20 ids.

	*/
	Ids []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the line status by ids params
func (o *LineStatusByIdsParams) WithTimeout(timeout time.Duration) *LineStatusByIdsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the line status by ids params
func (o *LineStatusByIdsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the line status by ids params
func (o *LineStatusByIdsParams) WithContext(ctx context.Context) *LineStatusByIdsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the line status by ids params
func (o *LineStatusByIdsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the line status by ids params
func (o *LineStatusByIdsParams) WithHTTPClient(client *http.Client) *LineStatusByIdsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the line status by ids params
func (o *LineStatusByIdsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDetail adds the detail to the line status by ids params
func (o *LineStatusByIdsParams) WithDetail(detail *bool) *LineStatusByIdsParams {
	o.SetDetail(detail)
	return o
}

// SetDetail adds the detail to the line status by ids params
func (o *LineStatusByIdsParams) SetDetail(detail *bool) {
	o.Detail = detail
}

// WithIds adds the ids to the line status by ids params
func (o *LineStatusByIdsParams) WithIds(ids []string) *LineStatusByIdsParams {
	o.SetIds(ids)
	return o
}

// SetIds adds the ids to the line status by ids params
func (o *LineStatusByIdsParams) SetIds(ids []string) {
	o.Ids = ids
}

// WriteToRequest writes these params to a swagger request
func (o *LineStatusByIdsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Detail != nil {

		// query param detail
		var qrDetail bool
		if o.Detail != nil {
			qrDetail = *o.Detail
		}
		qDetail := swag.FormatBool(qrDetail)
		if qDetail != "" {
			if err := r.SetQueryParam("detail", qDetail); err != nil {
				return err
			}
		}

	}

	valuesIds := o.Ids

	joinedIds := swag.JoinByFormat(valuesIds, "")
	// path array param ids
	// SetPathParam does not support variadric arguments, since we used JoinByFormat
	// we can send the first item in the array as it's all the items of the previous
	// array joined together
	if len(joinedIds) > 0 {
		if err := r.SetPathParam("ids", joinedIds[0]); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
