// Code generated by go-swagger; DO NOT EDIT.

package place

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPlaceMetaCategoriesParams creates a new PlaceMetaCategoriesParams object
// with the default values initialized.
func NewPlaceMetaCategoriesParams() *PlaceMetaCategoriesParams {

	return &PlaceMetaCategoriesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPlaceMetaCategoriesParamsWithTimeout creates a new PlaceMetaCategoriesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPlaceMetaCategoriesParamsWithTimeout(timeout time.Duration) *PlaceMetaCategoriesParams {

	return &PlaceMetaCategoriesParams{

		timeout: timeout,
	}
}

// NewPlaceMetaCategoriesParamsWithContext creates a new PlaceMetaCategoriesParams object
// with the default values initialized, and the ability to set a context for a request
func NewPlaceMetaCategoriesParamsWithContext(ctx context.Context) *PlaceMetaCategoriesParams {

	return &PlaceMetaCategoriesParams{

		Context: ctx,
	}
}

// NewPlaceMetaCategoriesParamsWithHTTPClient creates a new PlaceMetaCategoriesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPlaceMetaCategoriesParamsWithHTTPClient(client *http.Client) *PlaceMetaCategoriesParams {

	return &PlaceMetaCategoriesParams{
		HTTPClient: client,
	}
}

/*PlaceMetaCategoriesParams contains all the parameters to send to the API endpoint
for the place meta categories operation typically these are written to a http.Request
*/
type PlaceMetaCategoriesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the place meta categories params
func (o *PlaceMetaCategoriesParams) WithTimeout(timeout time.Duration) *PlaceMetaCategoriesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the place meta categories params
func (o *PlaceMetaCategoriesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the place meta categories params
func (o *PlaceMetaCategoriesParams) WithContext(ctx context.Context) *PlaceMetaCategoriesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the place meta categories params
func (o *PlaceMetaCategoriesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the place meta categories params
func (o *PlaceMetaCategoriesParams) WithHTTPClient(client *http.Client) *PlaceMetaCategoriesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the place meta categories params
func (o *PlaceMetaCategoriesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PlaceMetaCategoriesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
