// Code generated by go-swagger; DO NOT EDIT.

package place

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dwardu89/tfl-api-swagger/models"
)

// PlaceSearchReader is a Reader for the PlaceSearch structure.
type PlaceSearchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PlaceSearchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPlaceSearchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPlaceSearchOK creates a PlaceSearchOK with default headers values
func NewPlaceSearchOK() *PlaceSearchOK {
	return &PlaceSearchOK{}
}

/*PlaceSearchOK handles this case with default header values.

OK
*/
type PlaceSearchOK struct {
	Payload []*models.TflAPIPresentationEntitiesPlace
}

func (o *PlaceSearchOK) Error() string {
	return fmt.Sprintf("[GET /Place/Search][%d] placeSearchOK  %+v", 200, o.Payload)
}

func (o *PlaceSearchOK) GetPayload() []*models.TflAPIPresentationEntitiesPlace {
	return o.Payload
}

func (o *PlaceSearchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
