// Code generated by go-swagger; DO NOT EDIT.

package place

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dwardu89/tfl-api-swagger/models"
)

// PlaceGetReader is a Reader for the PlaceGet structure.
type PlaceGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PlaceGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPlaceGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPlaceGetOK creates a PlaceGetOK with default headers values
func NewPlaceGetOK() *PlaceGetOK {
	return &PlaceGetOK{}
}

/*PlaceGetOK handles this case with default header values.

OK
*/
type PlaceGetOK struct {
	Payload []*models.TflAPIPresentationEntitiesPlace
}

func (o *PlaceGetOK) Error() string {
	return fmt.Sprintf("[GET /Place/{id}][%d] placeGetOK  %+v", 200, o.Payload)
}

func (o *PlaceGetOK) GetPayload() []*models.TflAPIPresentationEntitiesPlace {
	return o.Payload
}

func (o *PlaceGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
