// Code generated by go-swagger; DO NOT EDIT.

package place

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dwardu89/tfl-api-swagger/models"
)

// PlaceMetaCategoriesReader is a Reader for the PlaceMetaCategories structure.
type PlaceMetaCategoriesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PlaceMetaCategoriesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPlaceMetaCategoriesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPlaceMetaCategoriesOK creates a PlaceMetaCategoriesOK with default headers values
func NewPlaceMetaCategoriesOK() *PlaceMetaCategoriesOK {
	return &PlaceMetaCategoriesOK{}
}

/*PlaceMetaCategoriesOK handles this case with default header values.

OK
*/
type PlaceMetaCategoriesOK struct {
	Payload []*models.TflAPIPresentationEntitiesPlaceCategory
}

func (o *PlaceMetaCategoriesOK) Error() string {
	return fmt.Sprintf("[GET /Place/Meta/Categories][%d] placeMetaCategoriesOK  %+v", 200, o.Payload)
}

func (o *PlaceMetaCategoriesOK) GetPayload() []*models.TflAPIPresentationEntitiesPlaceCategory {
	return o.Payload
}

func (o *PlaceMetaCategoriesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
