// Code generated by go-swagger; DO NOT EDIT.

package place

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dwardu89/tfl-api-swagger/models"
)

// PlaceGetStreetsByPostCodeReader is a Reader for the PlaceGetStreetsByPostCode structure.
type PlaceGetStreetsByPostCodeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PlaceGetStreetsByPostCodeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPlaceGetStreetsByPostCodeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPlaceGetStreetsByPostCodeOK creates a PlaceGetStreetsByPostCodeOK with default headers values
func NewPlaceGetStreetsByPostCodeOK() *PlaceGetStreetsByPostCodeOK {
	return &PlaceGetStreetsByPostCodeOK{}
}

/*PlaceGetStreetsByPostCodeOK handles this case with default header values.

OK
*/
type PlaceGetStreetsByPostCodeOK struct {
	Payload models.SystemObject
}

func (o *PlaceGetStreetsByPostCodeOK) Error() string {
	return fmt.Sprintf("[GET /Place/Address/Streets/{Postcode}][%d] placeGetStreetsByPostCodeOK  %+v", 200, o.Payload)
}

func (o *PlaceGetStreetsByPostCodeOK) GetPayload() models.SystemObject {
	return o.Payload
}

func (o *PlaceGetStreetsByPostCodeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
