// Code generated by go-swagger; DO NOT EDIT.

package place

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPlaceMetaPlaceTypesParams creates a new PlaceMetaPlaceTypesParams object
// with the default values initialized.
func NewPlaceMetaPlaceTypesParams() *PlaceMetaPlaceTypesParams {

	return &PlaceMetaPlaceTypesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPlaceMetaPlaceTypesParamsWithTimeout creates a new PlaceMetaPlaceTypesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPlaceMetaPlaceTypesParamsWithTimeout(timeout time.Duration) *PlaceMetaPlaceTypesParams {

	return &PlaceMetaPlaceTypesParams{

		timeout: timeout,
	}
}

// NewPlaceMetaPlaceTypesParamsWithContext creates a new PlaceMetaPlaceTypesParams object
// with the default values initialized, and the ability to set a context for a request
func NewPlaceMetaPlaceTypesParamsWithContext(ctx context.Context) *PlaceMetaPlaceTypesParams {

	return &PlaceMetaPlaceTypesParams{

		Context: ctx,
	}
}

// NewPlaceMetaPlaceTypesParamsWithHTTPClient creates a new PlaceMetaPlaceTypesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPlaceMetaPlaceTypesParamsWithHTTPClient(client *http.Client) *PlaceMetaPlaceTypesParams {

	return &PlaceMetaPlaceTypesParams{
		HTTPClient: client,
	}
}

/*PlaceMetaPlaceTypesParams contains all the parameters to send to the API endpoint
for the place meta place types operation typically these are written to a http.Request
*/
type PlaceMetaPlaceTypesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the place meta place types params
func (o *PlaceMetaPlaceTypesParams) WithTimeout(timeout time.Duration) *PlaceMetaPlaceTypesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the place meta place types params
func (o *PlaceMetaPlaceTypesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the place meta place types params
func (o *PlaceMetaPlaceTypesParams) WithContext(ctx context.Context) *PlaceMetaPlaceTypesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the place meta place types params
func (o *PlaceMetaPlaceTypesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the place meta place types params
func (o *PlaceMetaPlaceTypesParams) WithHTTPClient(client *http.Client) *PlaceMetaPlaceTypesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the place meta place types params
func (o *PlaceMetaPlaceTypesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PlaceMetaPlaceTypesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
