// Code generated by go-swagger; DO NOT EDIT.

package accident_stats

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new accident stats API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for accident stats API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
AccidentStatsGet gets all accident details for accidents occuring in the specified year
*/
func (a *Client) AccidentStatsGet(params *AccidentStatsGetParams) (*AccidentStatsGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAccidentStatsGetParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "AccidentStats_Get",
		Method:             "GET",
		PathPattern:        "/AccidentStats/{year}",
		ProducesMediaTypes: []string{"application/json", "application/xml", "text/json", "text/xml"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &AccidentStatsGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*AccidentStatsGetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for AccidentStats_Get: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
