// Code generated by go-swagger; DO NOT EDIT.

package accident_stats

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAccidentStatsGetParams creates a new AccidentStatsGetParams object
// with the default values initialized.
func NewAccidentStatsGetParams() *AccidentStatsGetParams {
	var ()
	return &AccidentStatsGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAccidentStatsGetParamsWithTimeout creates a new AccidentStatsGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAccidentStatsGetParamsWithTimeout(timeout time.Duration) *AccidentStatsGetParams {
	var ()
	return &AccidentStatsGetParams{

		timeout: timeout,
	}
}

// NewAccidentStatsGetParamsWithContext creates a new AccidentStatsGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewAccidentStatsGetParamsWithContext(ctx context.Context) *AccidentStatsGetParams {
	var ()
	return &AccidentStatsGetParams{

		Context: ctx,
	}
}

// NewAccidentStatsGetParamsWithHTTPClient creates a new AccidentStatsGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAccidentStatsGetParamsWithHTTPClient(client *http.Client) *AccidentStatsGetParams {
	var ()
	return &AccidentStatsGetParams{
		HTTPClient: client,
	}
}

/*AccidentStatsGetParams contains all the parameters to send to the API endpoint
for the accident stats get operation typically these are written to a http.Request
*/
type AccidentStatsGetParams struct {

	/*Year
	  The year for which to filter the accidents on.

	*/
	Year int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the accident stats get params
func (o *AccidentStatsGetParams) WithTimeout(timeout time.Duration) *AccidentStatsGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the accident stats get params
func (o *AccidentStatsGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the accident stats get params
func (o *AccidentStatsGetParams) WithContext(ctx context.Context) *AccidentStatsGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the accident stats get params
func (o *AccidentStatsGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the accident stats get params
func (o *AccidentStatsGetParams) WithHTTPClient(client *http.Client) *AccidentStatsGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the accident stats get params
func (o *AccidentStatsGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithYear adds the year to the accident stats get params
func (o *AccidentStatsGetParams) WithYear(year int32) *AccidentStatsGetParams {
	o.SetYear(year)
	return o
}

// SetYear adds the year to the accident stats get params
func (o *AccidentStatsGetParams) SetYear(year int32) {
	o.Year = year
}

// WriteToRequest writes these params to a swagger request
func (o *AccidentStatsGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param year
	if err := r.SetPathParam("year", swag.FormatInt32(o.Year)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
