// Code generated by go-swagger; DO NOT EDIT.

package search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// SearchMetaSearchProvidersReader is a Reader for the SearchMetaSearchProviders structure.
type SearchMetaSearchProvidersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchMetaSearchProvidersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSearchMetaSearchProvidersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSearchMetaSearchProvidersOK creates a SearchMetaSearchProvidersOK with default headers values
func NewSearchMetaSearchProvidersOK() *SearchMetaSearchProvidersOK {
	return &SearchMetaSearchProvidersOK{}
}

/*SearchMetaSearchProvidersOK handles this case with default header values.

OK
*/
type SearchMetaSearchProvidersOK struct {
	Payload []string
}

func (o *SearchMetaSearchProvidersOK) Error() string {
	return fmt.Sprintf("[GET /Search/Meta/SearchProviders][%d] searchMetaSearchProvidersOK  %+v", 200, o.Payload)
}

func (o *SearchMetaSearchProvidersOK) GetPayload() []string {
	return o.Payload
}

func (o *SearchMetaSearchProvidersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
