// Code generated by go-swagger; DO NOT EDIT.

package search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSearchMetaCategoriesParams creates a new SearchMetaCategoriesParams object
// with the default values initialized.
func NewSearchMetaCategoriesParams() *SearchMetaCategoriesParams {

	return &SearchMetaCategoriesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSearchMetaCategoriesParamsWithTimeout creates a new SearchMetaCategoriesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSearchMetaCategoriesParamsWithTimeout(timeout time.Duration) *SearchMetaCategoriesParams {

	return &SearchMetaCategoriesParams{

		timeout: timeout,
	}
}

// NewSearchMetaCategoriesParamsWithContext creates a new SearchMetaCategoriesParams object
// with the default values initialized, and the ability to set a context for a request
func NewSearchMetaCategoriesParamsWithContext(ctx context.Context) *SearchMetaCategoriesParams {

	return &SearchMetaCategoriesParams{

		Context: ctx,
	}
}

// NewSearchMetaCategoriesParamsWithHTTPClient creates a new SearchMetaCategoriesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSearchMetaCategoriesParamsWithHTTPClient(client *http.Client) *SearchMetaCategoriesParams {

	return &SearchMetaCategoriesParams{
		HTTPClient: client,
	}
}

/*SearchMetaCategoriesParams contains all the parameters to send to the API endpoint
for the search meta categories operation typically these are written to a http.Request
*/
type SearchMetaCategoriesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the search meta categories params
func (o *SearchMetaCategoriesParams) WithTimeout(timeout time.Duration) *SearchMetaCategoriesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search meta categories params
func (o *SearchMetaCategoriesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search meta categories params
func (o *SearchMetaCategoriesParams) WithContext(ctx context.Context) *SearchMetaCategoriesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search meta categories params
func (o *SearchMetaCategoriesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search meta categories params
func (o *SearchMetaCategoriesParams) WithHTTPClient(client *http.Client) *SearchMetaCategoriesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search meta categories params
func (o *SearchMetaCategoriesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *SearchMetaCategoriesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
