// Code generated by go-swagger; DO NOT EDIT.

package search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/dwardu89/tfl-api-swagger/models"
)

// SearchBusSchedulesReader is a Reader for the SearchBusSchedules structure.
type SearchBusSchedulesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchBusSchedulesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSearchBusSchedulesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSearchBusSchedulesOK creates a SearchBusSchedulesOK with default headers values
func NewSearchBusSchedulesOK() *SearchBusSchedulesOK {
	return &SearchBusSchedulesOK{}
}

/*SearchBusSchedulesOK handles this case with default header values.

OK
*/
type SearchBusSchedulesOK struct {
	Payload *models.TflAPIPresentationEntitiesSearchResponse
}

func (o *SearchBusSchedulesOK) Error() string {
	return fmt.Sprintf("[GET /Search/BusSchedules][%d] searchBusSchedulesOK  %+v", 200, o.Payload)
}

func (o *SearchBusSchedulesOK) GetPayload() *models.TflAPIPresentationEntitiesSearchResponse {
	return o.Payload
}

func (o *SearchBusSchedulesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TflAPIPresentationEntitiesSearchResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
