// Code generated by go-swagger; DO NOT EDIT.

package search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSearchBusSchedulesParams creates a new SearchBusSchedulesParams object
// with the default values initialized.
func NewSearchBusSchedulesParams() *SearchBusSchedulesParams {
	var ()
	return &SearchBusSchedulesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSearchBusSchedulesParamsWithTimeout creates a new SearchBusSchedulesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSearchBusSchedulesParamsWithTimeout(timeout time.Duration) *SearchBusSchedulesParams {
	var ()
	return &SearchBusSchedulesParams{

		timeout: timeout,
	}
}

// NewSearchBusSchedulesParamsWithContext creates a new SearchBusSchedulesParams object
// with the default values initialized, and the ability to set a context for a request
func NewSearchBusSchedulesParamsWithContext(ctx context.Context) *SearchBusSchedulesParams {
	var ()
	return &SearchBusSchedulesParams{

		Context: ctx,
	}
}

// NewSearchBusSchedulesParamsWithHTTPClient creates a new SearchBusSchedulesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSearchBusSchedulesParamsWithHTTPClient(client *http.Client) *SearchBusSchedulesParams {
	var ()
	return &SearchBusSchedulesParams{
		HTTPClient: client,
	}
}

/*SearchBusSchedulesParams contains all the parameters to send to the API endpoint
for the search bus schedules operation typically these are written to a http.Request
*/
type SearchBusSchedulesParams struct {

	/*Query
	  The search query

	*/
	Query string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the search bus schedules params
func (o *SearchBusSchedulesParams) WithTimeout(timeout time.Duration) *SearchBusSchedulesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search bus schedules params
func (o *SearchBusSchedulesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search bus schedules params
func (o *SearchBusSchedulesParams) WithContext(ctx context.Context) *SearchBusSchedulesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search bus schedules params
func (o *SearchBusSchedulesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search bus schedules params
func (o *SearchBusSchedulesParams) WithHTTPClient(client *http.Client) *SearchBusSchedulesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search bus schedules params
func (o *SearchBusSchedulesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithQuery adds the query to the search bus schedules params
func (o *SearchBusSchedulesParams) WithQuery(query string) *SearchBusSchedulesParams {
	o.SetQuery(query)
	return o
}

// SetQuery adds the query to the search bus schedules params
func (o *SearchBusSchedulesParams) SetQuery(query string) {
	o.Query = query
}

// WriteToRequest writes these params to a swagger request
func (o *SearchBusSchedulesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param query
	qrQuery := o.Query
	qQuery := qrQuery
	if qQuery != "" {
		if err := r.SetQueryParam("query", qQuery); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
