// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SystemDataSpatialDbGeography system data spatial db geography
// swagger:model System.Data.Spatial.DbGeography
type SystemDataSpatialDbGeography struct {

	// geography
	Geography *SystemDataSpatialDbGeographyWellKnownValue `json:"geography,omitempty"`
}

// Validate validates this system data spatial db geography
func (m *SystemDataSpatialDbGeography) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGeography(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SystemDataSpatialDbGeography) validateGeography(formats strfmt.Registry) error {

	if swag.IsZero(m.Geography) { // not required
		return nil
	}

	if m.Geography != nil {
		if err := m.Geography.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("geography")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SystemDataSpatialDbGeography) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SystemDataSpatialDbGeography) UnmarshalBinary(b []byte) error {
	var res SystemDataSpatialDbGeography
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
