// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TflAPIPresentationEntitiesJourneyPlannerRouteOption tfl Api presentation entities journey planner route option
// swagger:model Tfl.Api.Presentation.Entities.JourneyPlanner.RouteOption
type TflAPIPresentationEntitiesJourneyPlannerRouteOption struct {

	// directions
	Directions []string `json:"directions"`

	// The Id of the route
	ID string `json:"id,omitempty"`

	// The line identifier (e.g. District Line), from where you can obtain line status information e.g. the rainbow board status "good service".
	LineIdentifier *TflAPIPresentationEntitiesIdentifier `json:"lineIdentifier,omitempty"`

	// Name such as "72"
	Name string `json:"name,omitempty"`
}

// Validate validates this tfl Api presentation entities journey planner route option
func (m *TflAPIPresentationEntitiesJourneyPlannerRouteOption) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLineIdentifier(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TflAPIPresentationEntitiesJourneyPlannerRouteOption) validateLineIdentifier(formats strfmt.Registry) error {

	if swag.IsZero(m.LineIdentifier) { // not required
		return nil
	}

	if m.LineIdentifier != nil {
		if err := m.LineIdentifier.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("lineIdentifier")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesJourneyPlannerRouteOption) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesJourneyPlannerRouteOption) UnmarshalBinary(b []byte) error {
	var res TflAPIPresentationEntitiesJourneyPlannerRouteOption
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
