// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TflAPIPresentationEntitiesStationInterval tfl Api presentation entities station interval
// swagger:model Tfl.Api.Presentation.Entities.StationInterval
type TflAPIPresentationEntitiesStationInterval struct {

	// id
	ID string `json:"id,omitempty"`

	// intervals
	Intervals []*TflAPIPresentationEntitiesInterval `json:"intervals"`
}

// Validate validates this tfl Api presentation entities station interval
func (m *TflAPIPresentationEntitiesStationInterval) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIntervals(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TflAPIPresentationEntitiesStationInterval) validateIntervals(formats strfmt.Registry) error {

	if swag.IsZero(m.Intervals) { // not required
		return nil
	}

	for i := 0; i < len(m.Intervals); i++ {
		if swag.IsZero(m.Intervals[i]) { // not required
			continue
		}

		if m.Intervals[i] != nil {
			if err := m.Intervals[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("intervals" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesStationInterval) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesStationInterval) UnmarshalBinary(b []byte) error {
	var res TflAPIPresentationEntitiesStationInterval
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
