// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TflAPIPresentationEntitiesFaresRecommendationResponse tfl Api presentation entities fares recommendation response
// swagger:model Tfl.Api.Presentation.Entities.Fares.RecommendationResponse
type TflAPIPresentationEntitiesFaresRecommendationResponse struct {

	// recommendations
	Recommendations []*TflAPIPresentationEntitiesFaresRecommendation `json:"recommendations"`
}

// Validate validates this tfl Api presentation entities fares recommendation response
func (m *TflAPIPresentationEntitiesFaresRecommendationResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRecommendations(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TflAPIPresentationEntitiesFaresRecommendationResponse) validateRecommendations(formats strfmt.Registry) error {

	if swag.IsZero(m.Recommendations) { // not required
		return nil
	}

	for i := 0; i < len(m.Recommendations); i++ {
		if swag.IsZero(m.Recommendations[i]) { // not required
			continue
		}

		if m.Recommendations[i] != nil {
			if err := m.Recommendations[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("recommendations" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesFaresRecommendationResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesFaresRecommendationResponse) UnmarshalBinary(b []byte) error {
	var res TflAPIPresentationEntitiesFaresRecommendationResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
