// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TflAPIPresentationEntitiesJourneyPlannerTimeAdjustments tfl Api presentation entities journey planner time adjustments
// swagger:model Tfl.Api.Presentation.Entities.JourneyPlanner.TimeAdjustments
type TflAPIPresentationEntitiesJourneyPlannerTimeAdjustments struct {

	// earlier
	Earlier *TflAPIPresentationEntitiesJourneyPlannerTimeAdjustment `json:"earlier,omitempty"`

	// earliest
	Earliest *TflAPIPresentationEntitiesJourneyPlannerTimeAdjustment `json:"earliest,omitempty"`

	// later
	Later *TflAPIPresentationEntitiesJourneyPlannerTimeAdjustment `json:"later,omitempty"`

	// latest
	Latest *TflAPIPresentationEntitiesJourneyPlannerTimeAdjustment `json:"latest,omitempty"`
}

// Validate validates this tfl Api presentation entities journey planner time adjustments
func (m *TflAPIPresentationEntitiesJourneyPlannerTimeAdjustments) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEarlier(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEarliest(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLater(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLatest(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TflAPIPresentationEntitiesJourneyPlannerTimeAdjustments) validateEarlier(formats strfmt.Registry) error {

	if swag.IsZero(m.Earlier) { // not required
		return nil
	}

	if m.Earlier != nil {
		if err := m.Earlier.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("earlier")
			}
			return err
		}
	}

	return nil
}

func (m *TflAPIPresentationEntitiesJourneyPlannerTimeAdjustments) validateEarliest(formats strfmt.Registry) error {

	if swag.IsZero(m.Earliest) { // not required
		return nil
	}

	if m.Earliest != nil {
		if err := m.Earliest.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("earliest")
			}
			return err
		}
	}

	return nil
}

func (m *TflAPIPresentationEntitiesJourneyPlannerTimeAdjustments) validateLater(formats strfmt.Registry) error {

	if swag.IsZero(m.Later) { // not required
		return nil
	}

	if m.Later != nil {
		if err := m.Later.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("later")
			}
			return err
		}
	}

	return nil
}

func (m *TflAPIPresentationEntitiesJourneyPlannerTimeAdjustments) validateLatest(formats strfmt.Registry) error {

	if swag.IsZero(m.Latest) { // not required
		return nil
	}

	if m.Latest != nil {
		if err := m.Latest.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("latest")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesJourneyPlannerTimeAdjustments) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesJourneyPlannerTimeAdjustments) UnmarshalBinary(b []byte) error {
	var res TflAPIPresentationEntitiesJourneyPlannerTimeAdjustments
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
