// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TflAPIPresentationEntitiesCrowding tfl Api presentation entities crowding
// swagger:model Tfl.Api.Presentation.Entities.Crowding
type TflAPIPresentationEntitiesCrowding struct {

	// Busiest times at a station (static information)
	PassengerFlows []*TflAPIPresentationEntitiesPassengerFlow `json:"passengerFlows"`

	// Train Loading on a scale 1-6, 1 being "Very quiet" and 6 being "Exceptionally busy" (static information)
	TrainLoadings []*TflAPIPresentationEntitiesTrainLoading `json:"trainLoadings"`
}

// Validate validates this tfl Api presentation entities crowding
func (m *TflAPIPresentationEntitiesCrowding) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePassengerFlows(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTrainLoadings(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TflAPIPresentationEntitiesCrowding) validatePassengerFlows(formats strfmt.Registry) error {

	if swag.IsZero(m.PassengerFlows) { // not required
		return nil
	}

	for i := 0; i < len(m.PassengerFlows); i++ {
		if swag.IsZero(m.PassengerFlows[i]) { // not required
			continue
		}

		if m.PassengerFlows[i] != nil {
			if err := m.PassengerFlows[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("passengerFlows" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *TflAPIPresentationEntitiesCrowding) validateTrainLoadings(formats strfmt.Registry) error {

	if swag.IsZero(m.TrainLoadings) { // not required
		return nil
	}

	for i := 0; i < len(m.TrainLoadings); i++ {
		if swag.IsZero(m.TrainLoadings[i]) { // not required
			continue
		}

		if m.TrainLoadings[i] != nil {
			if err := m.TrainLoadings[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("trainLoadings" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesCrowding) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesCrowding) UnmarshalBinary(b []byte) error {
	var res TflAPIPresentationEntitiesCrowding
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
