// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TflAPIPresentationEntitiesJourneyPlannerJourneyFare tfl Api presentation entities journey planner journey fare
// swagger:model Tfl.Api.Presentation.Entities.JourneyPlanner.JourneyFare
type TflAPIPresentationEntitiesJourneyPlannerJourneyFare struct {

	// caveats
	Caveats []*TflAPIPresentationEntitiesJourneyPlannerFareCaveat `json:"caveats"`

	// fares
	Fares []*TflAPIPresentationEntitiesJourneyPlannerFare `json:"fares"`

	// total cost
	TotalCost int32 `json:"totalCost,omitempty"`
}

// Validate validates this tfl Api presentation entities journey planner journey fare
func (m *TflAPIPresentationEntitiesJourneyPlannerJourneyFare) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCaveats(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFares(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TflAPIPresentationEntitiesJourneyPlannerJourneyFare) validateCaveats(formats strfmt.Registry) error {

	if swag.IsZero(m.Caveats) { // not required
		return nil
	}

	for i := 0; i < len(m.Caveats); i++ {
		if swag.IsZero(m.Caveats[i]) { // not required
			continue
		}

		if m.Caveats[i] != nil {
			if err := m.Caveats[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("caveats" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *TflAPIPresentationEntitiesJourneyPlannerJourneyFare) validateFares(formats strfmt.Registry) error {

	if swag.IsZero(m.Fares) { // not required
		return nil
	}

	for i := 0; i < len(m.Fares); i++ {
		if swag.IsZero(m.Fares[i]) { // not required
			continue
		}

		if m.Fares[i] != nil {
			if err := m.Fares[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("fares" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesJourneyPlannerJourneyFare) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesJourneyPlannerJourneyFare) UnmarshalBinary(b []byte) error {
	var res TflAPIPresentationEntitiesJourneyPlannerJourneyFare
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
