// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TflAPIPresentationEntitiesJourneyPlannerPath tfl Api presentation entities journey planner path
// swagger:model Tfl.Api.Presentation.Entities.JourneyPlanner.Path
type TflAPIPresentationEntitiesJourneyPlannerPath struct {

	// elevation
	Elevation []*TflAPICommonJourneyPlannerJpElevation `json:"elevation"`

	// line string
	LineString string `json:"lineString,omitempty"`

	// stop points
	StopPoints []*TflAPIPresentationEntitiesIdentifier `json:"stopPoints"`
}

// Validate validates this tfl Api presentation entities journey planner path
func (m *TflAPIPresentationEntitiesJourneyPlannerPath) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateElevation(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStopPoints(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TflAPIPresentationEntitiesJourneyPlannerPath) validateElevation(formats strfmt.Registry) error {

	if swag.IsZero(m.Elevation) { // not required
		return nil
	}

	for i := 0; i < len(m.Elevation); i++ {
		if swag.IsZero(m.Elevation[i]) { // not required
			continue
		}

		if m.Elevation[i] != nil {
			if err := m.Elevation[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("elevation" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *TflAPIPresentationEntitiesJourneyPlannerPath) validateStopPoints(formats strfmt.Registry) error {

	if swag.IsZero(m.StopPoints) { // not required
		return nil
	}

	for i := 0; i < len(m.StopPoints); i++ {
		if swag.IsZero(m.StopPoints[i]) { // not required
			continue
		}

		if m.StopPoints[i] != nil {
			if err := m.StopPoints[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("stopPoints" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesJourneyPlannerPath) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesJourneyPlannerPath) UnmarshalBinary(b []byte) error {
	var res TflAPIPresentationEntitiesJourneyPlannerPath
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
