// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TflAPIPresentationEntitiesFaresJourney tfl Api presentation entities fares journey
// swagger:model Tfl.Api.Presentation.Entities.Fares.Journey
type TflAPIPresentationEntitiesFaresJourney struct {

	// from station
	FromStation *TflAPIPresentationEntitiesFaresFareStation `json:"fromStation,omitempty"`

	// to station
	ToStation *TflAPIPresentationEntitiesFaresFareStation `json:"toStation,omitempty"`
}

// Validate validates this tfl Api presentation entities fares journey
func (m *TflAPIPresentationEntitiesFaresJourney) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFromStation(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateToStation(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TflAPIPresentationEntitiesFaresJourney) validateFromStation(formats strfmt.Registry) error {

	if swag.IsZero(m.FromStation) { // not required
		return nil
	}

	if m.FromStation != nil {
		if err := m.FromStation.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("fromStation")
			}
			return err
		}
	}

	return nil
}

func (m *TflAPIPresentationEntitiesFaresJourney) validateToStation(formats strfmt.Registry) error {

	if swag.IsZero(m.ToStation) { // not required
		return nil
	}

	if m.ToStation != nil {
		if err := m.ToStation.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("toStation")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesFaresJourney) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesFaresJourney) UnmarshalBinary(b []byte) error {
	var res TflAPIPresentationEntitiesFaresJourney
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
