// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TflAPIPresentationEntitiesRouteSequence tfl Api presentation entities route sequence
// swagger:model Tfl.Api.Presentation.Entities.RouteSequence
type TflAPIPresentationEntitiesRouteSequence struct {

	// direction
	Direction string `json:"direction,omitempty"`

	// is outbound only
	IsOutboundOnly bool `json:"isOutboundOnly,omitempty"`

	// line Id
	LineID string `json:"lineId,omitempty"`

	// line name
	LineName string `json:"lineName,omitempty"`

	// line strings
	LineStrings []string `json:"lineStrings"`

	// mode
	Mode string `json:"mode,omitempty"`

	// ordered line routes
	OrderedLineRoutes []*TflAPIPresentationEntitiesOrderedRoute `json:"orderedLineRoutes"`

	// stations
	Stations []*TflAPIPresentationEntitiesMatchedStop `json:"stations"`

	// stop point sequences
	StopPointSequences []*TflAPIPresentationEntitiesStopPointSequence `json:"stopPointSequences"`
}

// Validate validates this tfl Api presentation entities route sequence
func (m *TflAPIPresentationEntitiesRouteSequence) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOrderedLineRoutes(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStations(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStopPointSequences(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TflAPIPresentationEntitiesRouteSequence) validateOrderedLineRoutes(formats strfmt.Registry) error {

	if swag.IsZero(m.OrderedLineRoutes) { // not required
		return nil
	}

	for i := 0; i < len(m.OrderedLineRoutes); i++ {
		if swag.IsZero(m.OrderedLineRoutes[i]) { // not required
			continue
		}

		if m.OrderedLineRoutes[i] != nil {
			if err := m.OrderedLineRoutes[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("orderedLineRoutes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *TflAPIPresentationEntitiesRouteSequence) validateStations(formats strfmt.Registry) error {

	if swag.IsZero(m.Stations) { // not required
		return nil
	}

	for i := 0; i < len(m.Stations); i++ {
		if swag.IsZero(m.Stations[i]) { // not required
			continue
		}

		if m.Stations[i] != nil {
			if err := m.Stations[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("stations" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *TflAPIPresentationEntitiesRouteSequence) validateStopPointSequences(formats strfmt.Registry) error {

	if swag.IsZero(m.StopPointSequences) { // not required
		return nil
	}

	for i := 0; i < len(m.StopPointSequences); i++ {
		if swag.IsZero(m.StopPointSequences[i]) { // not required
			continue
		}

		if m.StopPointSequences[i] != nil {
			if err := m.StopPointSequences[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("stopPointSequences" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesRouteSequence) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TflAPIPresentationEntitiesRouteSequence) UnmarshalBinary(b []byte) error {
	var res TflAPIPresentationEntitiesRouteSequence
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
